# Generated by Django 5.2 on 2025-05-05 06:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='sale',
            name='product_name',
            field=models.CharField(max_length=255),
        ),
    ]
