# Generated by Django 5.2 on 2025-05-05 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('MyPanel', '0002_alter_sale_date_alter_sale_product_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('deadline', models.DateField()),
            ],
        ),
    ]
